"""empty message

Revision ID: 0b3ba0d8a9c4
Revises: b1dab74ad4e8
Create Date: 2019-09-28 16:57:50.071409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3ba0d8a9c4'
down_revision = 'b1dab74ad4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialstatistics', 'display')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialstatistics', sa.Column('display', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
