"""empty message

Revision ID: 426e79cdcf86
Revises: d2eccecbd7d2
Create Date: 2019-11-02 14:38:10.805052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426e79cdcf86'
down_revision = 'd2eccecbd7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialmedia', sa.Column('type', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialmedia', 'type')
    # ### end Alembic commands ###
