"""empty message

Revision ID: b1dab74ad4e8
Revises: 8a08135236cf
Create Date: 2019-09-28 15:58:11.963188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dab74ad4e8'
down_revision = '8a08135236cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialmedia', sa.Column('media_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialmedia', 'media_url')
    # ### end Alembic commands ###
